// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfVsHIgndwVh7NTJnRi1PH7t2bt6cJVo',
    appId: '1:53750888434:web:c0dd8954b23069cb05dd6b',
    messagingSenderId: '53750888434',
    projectId: 'teach-video',
    authDomain: 'teach-video.firebaseapp.com',
    storageBucket: 'teach-video.appspot.com',
    measurementId: 'G-WQBQLX5WGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEZA_-vs3r8FjAQX_0LCQqs7zyAv3pvkU',
    appId: '1:53750888434:android:e400dba2cd6c9b2105dd6b',
    messagingSenderId: '53750888434',
    projectId: 'teach-video',
    storageBucket: 'teach-video.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUKPxJVPR_7SEVJM9z2VoTZi7845QPto',
    appId: '1:53750888434:ios:5d9ba9fe89a3b43005dd6b',
    messagingSenderId: '53750888434',
    projectId: 'teach-video',
    storageBucket: 'teach-video.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkUKPxJVPR_7SEVJM9z2VoTZi7845QPto',
    appId: '1:53750888434:ios:7971cf82bf41731305dd6b',
    messagingSenderId: '53750888434',
    projectId: 'teach-video',
    storageBucket: 'teach-video.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
